#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

echo "Running ESLint..."

# Run ESLint and ignore warnings
npx eslint . --max-warnings=-1
ESLINT_EXIT_CODE=$?

if [ $ESLINT_EXIT_CODE -ne 0 ]; then
  echo "❌ ESLint found errors. Commit aborted."
  exit 1
fi

echo "✅ ESLint通过啦，接下来进行commit..."
exit 0